### ISSUE TITLE
Laravel 6+ Support

### ISSUE THREAD

**Issue by ralphjesy12** [papertank/origami-consent#1]
```
Problem 1
    - Installation request for origami/consent ^0.2.3 -> satisfiable by origami/consent[0.2.3].
    - Conclusion: remove laravel/framework v6.0.4
    - origami/consent 0.2.3 requires illuminate/support ~5.4 
```

**Comment by davidrushton** [comment]
@ralphjesy12 Would you be able to submit a PR or test against your 6.0 installation?

I think updating the composer.json to use `~5.4|^6.0` should do the trick, but I don't have a v6 project using this package to test with.

**Comment by davidrushton** [comment]
@ralphjesy12 This should be fixed now.

You can either `composer update` depending on your version constraint, or update your composer.json to have `"origami/consent": "^0.3",`
