### ISSUE TITLE
Laravel 7+ support ?

### ISSUE THREAD

**Issue by Nuranto** [papertank/origami-consent#2]
```origami/consent 0.3.0 requires illuminate/support ~5.4|^6.0```

**Comment by Nuranto** [comment]
@davidrushton 
I think there is nothing else to change but the composer file... If I PR that, will you merge it ?

**Comment by davidrushton** [comment]
@Nuranto Yes, sure thanks. I think changing the illuminate versions to `^6.0|^7.0` should work. Are you happy to PR that and test on your project? 

I would probably tag as `0.4.0` as this is technically still beta. Sound ok?

**Comment by davidrushton** [comment]
@Nuranto You can update your composer.json to require `"origami/consent": "^0.4.0"` for Laravel 7 support.

**Comment by Nuranto** [comment]
@davidrushton Thank you very much, I was going to PR this today, but you were faster, so that's great. 
I will give you feed back in case of trouble with L7.
Have a beautiful week end!
