### ISSUE TITLE
PHP 8.0 support ?

### ISSUE THREAD

**Issue by Nuranto** [papertank/origami-consent#4]

**Comment by davidrushton** [comment]
@Nuranto I don't see any reason the package wouldn't be compatible with PHP 8, but you're welcome to submit a PR if you identify any issues and patch them.

**Comment by Nuranto** [comment]
@davidrushton Actually I already use it with PHP8.0, and I saw no issue with it.
It is just annoying to have to add `--ignore-platform-reqs` on each composer install/update commands.

I think, the only change needed is adding php 8.0 support in composer.json

**Comment by davidrushton** [comment]
@Nuranto Sure, no problem! I've added that to the todo list and will let you know when that's done.

**Comment by dsbilling** [comment]
`- origami/consent 2.0.0 requires php ^7.2 -> your php version (8.0.8) does not satisfy that requirement.`

Does not seem to support PHP8. Got a update? :)

**Comment by davidrushton** [comment]
This is merged now. Thanks @DanielRTRD
